source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.0.2'

gem 'pg'
gem 'puma', '~> 4.1'
gem 'rails', '~> 6.0.3', '>= 6.0.3.3'
# gem 'turbolinks', '~> 5'
gem 'bitly'
gem 'coffee-rails'
gem 'countries'
gem 'jbuilder', '~> 2.7'
gem 'jquery'
gem 'jquery-rails'
gem 'oanda_api_v20'
gem 'rubocop'
gem 'sidekiq'
gem 'twilio-ruby'
gem 'uglifier'
# gem 'pwa'
# bitly predict clicks, ratios, and income #sprint2
gem 'activerecord-session_store'
gem 'flag-icons-rails'
gem 'mimemagic', github: 'mimemagicrb/mimemagic', ref: '01f92d86d15d85cfd0f20dabd025dcbd36a8a60f'
gem 'social-share-button'

gem 'activesupport'
gem 'awesome_print'
gem 'byebug'
gem 'carrierwave'
gem 'clockwork'
gem 'cloudinary'
gem 'curb'
gem 'devise'
gem 'faker'
gem 'faraday'
gem 'figaro'
gem 'font-awesome-rails'
gem 'friendly_id'
gem 'geocoder'
gem 'media_embed'
gem 'oj'
gem 'simple_token_authentication'
gem 'stripe'
gem 'tradier'
gem 'will_paginate'
gem 'will_paginate-bootstrap4'

gem 'bootsnap', '>= 1.1.0', require: false

group :development do
  gem 'listen'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'web-console', '>= 3.3.0'
end

group :test do
  gem 'capybara'
  gem 'email_spec'
  gem 'factory_bot_rails'
  gem 'guard-rspec'
  gem 'letter_opener'
  gem 'rails-controller-testing'
  gem 'rspec'
  gem 'rspec-its'
  gem 'rspec-rails'
  gem 'shoulda'
  gem 'shoulda-matchers'
  gem 'test-unit'
end
